---
########################################
# Fabric Topology
########################################

# Spine Switches
spine:
  defaults:
    platform: ceos
    bgp_as: 65001
    loopback_ipv4_pool: 192.0.255.0/24
    mlag: false
  nodes:
    - name: spine1
      id: 1
      mgmt_ip: "{{ cookiecutter.oob_subnet | generate_ip_with_subnet(10) }}"
    - name: spine2
      id: 2
      mgmt_ip: "{{ cookiecutter.oob_subnet | generate_ip_with_subnet(11) }}"
# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

